#!/usr/bin/env python3
"""Main environment to solve the one dimensional time independent schrodinger
equation for different potentials. It writes the energies into energies.dat,
the wavefunctions into wavefuncs.dat, the potential into potential.dat and
the expected values of the position into expvalues.dat."""

import argparse
import numpy as np
from calculus._file_io import _read_schrodinger, _create_files
from calculus.calc import (pot_calc, solve_seq, _get_wf_array, _get_exp_unc,
                           expected_values, uncertainty_x)


_DESCRIPTION = """
Solves the schrodinger equation for various problems."""


def _clparsing():
    """Takes inputs from the command line and passes them to the program

    Returns:
        Object: Object storing chosen attributes
    """
    parser = argparse.ArgumentParser(description=_DESCRIPTION)

    msg = 'Path of the input file'
    parser.add_argument('-id', '--indir', default='.', help=msg)

    msg = 'Path of the output file'
    parser.add_argument('-od', '--outdir', default='.', help=msg)

    args = parser.parse_args()

    return args


_DIRECTORY = 'files'

_FILE = 'schrodinger.inp'


def main():
    """Main function to solve the one dimensional time independent schrodinger
    equation.
    """
    args = _clparsing()
    indirectory = args.indir
    outdirectory = args.outdir
    # Read out the informations of the schrodinger.inp file.
    inp = _read_schrodinger(indirectory, _FILE)

    xplot = np.linspace(inp['xmin'], inp['xmax'], num=inp['npoint'],
                        endpoint=True)

    pot = pot_calc(xplot, inp['pot'], inp['reg_type'])

    energy, evec = solve_seq(inp['xmin'], inp['xmax'], inp['npoint'],
                             inp['mass'], pot)

    energy = energy[inp['min_ev'] - 1: inp['max_ev']]

    xevec = _get_wf_array(xplot, inp['min_ev'], inp['max_ev'], evec)

    expectedx = expected_values(xplot, evec, inp['min_ev'], inp['max_ev'])

    uncertainty = uncertainty_x(xplot, evec, inp['min_ev'], inp['max_ev'])

    exp_values = _get_exp_unc(expectedx, uncertainty)

    x_pot = np.transpose(np.vstack((xplot, pot)))

    _create_files(outdirectory, energy, exp_values, x_pot, xevec)


if __name__ == '__main__':
    main()
