#!/usr/bin/env python3
"""This script visualizes the wavefunctions of a given potential. It also shows
the expected values of the position and the corresponding uncertainties."""


import argparse
import numpy as np
import calculus


_DESCRIPTION = """
Visualizes the solution of the schrodinger equation."""


def _clparsing():
    """Takes inputs from the command line and passes them to the program

    Returns:
        dic: Dictionary including the user input from the command line
    """
    parser = argparse.ArgumentParser(description=_DESCRIPTION)

    msg = 'Path of the input file'
    parser.add_argument('-sd', '--sinpdir', default='.', help=msg)

    msg = 'Path of the data files'
    parser.add_argument('-dd', '--dinpdir', default='.', help=msg)

    msg = 'Scaling factor for the wavefunctions'
    parser.add_argument('-s', '--scale', default=None, help=msg)

    args = parser.parse_args()

    return args


def main():
    """Main function to show the plot of the potential, the eigenvalues, the
    wavefunctions, the expected values of the position of the particle. It
    reads out the data which were calculated by the solver.
    """
    args = _clparsing()
    sinpdir = args.sinpdir
    dinpdir = args.dinpdir
    scale = args.scale

    data = calculus.file_io.read_files(dinpdir)
    energy = data[0]
    xplot = data[2][:, 0]
    pot = data[2][:, 1:]
    evec = data[3][:, 1:]

    xmin = np.amin(xplot)
    xmax = np.amax(xplot)

    inp = calculus.file_io.read_schrodinger(sinpdir, 'schrodinger.inp')
    min_ev = inp['_MIN_EV']
    max_ev = inp['_MAX_EV']

    if min_ev < max_ev:
        expectedx = data[1][:, 0]
        uncertainty = data[1][:, 1]
    elif min_ev == max_ev:
        expectedx = data[1][0]
        uncertainty = data[1][1]

    if min_ev < max_ev:
        ydiff = abs(energy[max_ev - 1] - np.amin(pot))
    elif min_ev == max_ev:
        ydiff = abs(energy - np.amin(pot))

    if min_ev < max_ev:
        calculus.plot.pot_plot_multi(xmin, xmax, min_ev, max_ev, energy, evec,
                                     pot, xplot, ydiff, expectedx, uncertainty)
    else:
        calculus.plot.pot_plot_one(xmin, xmax, min_ev, max_ev, energy, evec,
                                   pot, xplot, ydiff, expectedx, uncertainty)


if __name__ == '__main__':
    main()
